stages:
  - test
  - build
  - package
  - e2e
  - cleanup
  - release

unit-test-backend:
  stage: test
  image: python:3.11-alpine
  script:
    - pip install pipenv
    - cd backend
    - pipenv install --dev
    - pipenv run coverage run -m pytest --junitxml=report.xml tests/unit
    - pipenv run coverage report
    - pipenv run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: backend/report.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml

build-backend:
  stage: build
  image: python:3.11-alpine
  script:
    - pip install pipenv
    - cd backend
    - pipenv install --dev
    - pipenv run python3 -m build
  artifacts:
    paths:
      - backend/dist
    expire_in: 1 hour

containerize-frontend:
  stage: package
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build frontend -t ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    - podman push ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}

containerize-backend:
  stage: package
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build backend -t ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} --build-arg context=ci
    - podman push ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}

containerize-reverse-proxy:
  stage: package
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build reverse-proxy -t ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
    - podman push ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}

# e2e-test:
#   stage: e2e
#   image: quay.io/podman/stable
#   variables:
#     GCD_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/gcd:${CI_COMMIT_REF_SLUG}
#   before_script:
#     - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
#   script:
#     - apk add --update python3
#     - python3 -m ensurepip
#     - pip3 install pipenv
#     - pipenv install --dev
#     - pipenv run behave tests/e2e
#   after_script:
#     - podman rmi ${CI_REGISTRY_IMAGE}/gcd:${CI_COMMIT_REF_SLUG}

remove-container:
  stage: cleanup
  image: 
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  before_script:
    - /bin/skopeo login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
  except:
    variables:
      - $CI_COMMIT_TAG

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
      when: manual
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - release-cli create
        --name "Turing-${CI_COMMIT_TAG}"
        --description "A docker image is available at ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG} & ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} or with the latest tag"
        --tag-name "${CI_COMMIT_TAG}"

add-latest-tag:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
  needs:
    - 'release'
  image: 
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  before_script:
    - /bin/skopeo login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/frontend:latest
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/backend:latest
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/reverse-proxy:latest
