stages:
  - test
  - build
  - package
  - e2e
  - cleanup
  - release

include:
  - template: Security/Container-Scanning.gitlab-ci.yml

unit-test-backend:
  stage: test
  image: python:3.11-alpine
  script:
    - pip install pipenv
    - cd backend
    - pipenv install --dev
    - pipenv run coverage run -m pytest --junitxml=report.xml tests/unit
    - pipenv run coverage report
    - pipenv run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: backend/report.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml

build-backend:
  stage: build
  dependencies: []
  image: python:3.11-alpine
  script:
    - pip install pipenv
    - cd backend
    - pipenv install --dev
    - pipenv run python3 -m build
  artifacts:
    paths:
      - backend/dist
    expire_in: 1 hour

containerize-frontend:
  stage: package
  dependencies: []
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build frontend -t ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    - podman push ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}

containerize-backend:
  stage: package
  dependencies:
    - build-backend
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build backend -t ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} --build-arg context=ci
    - podman push ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}

containerize-reverse-proxy:
  stage: package
  dependencies: []
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - podman build reverse-proxy -t ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
    - podman push ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
  after_script:
    - podman rmi ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}

e2e-test:
  stage: e2e
  dependencies: []
  image: docker:24-dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - |
      echo -e "version: '2'
      services:
        backend:
          image: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
        frontend:
          image: ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
        reverse-proxy:
          image: ${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
          ports: [80]" > compose.e2e.yml
    - cat compose.e2e.yml
    - docker compose -f compose.e2e.yml up --detach
    - cat enigma.yaml | docker compose -f compose.e2e.yml exec -i backend tee /etc/enigma.yaml
    - export MAIN_SERVICE=$(docker compose -f compose.e2e.yml port reverse-proxy 80)
    - docker build e2e_enigma -t e2e-tests:${CI_COMMIT_REF_SLUG} -f e2e_enigma/Containerfile
    - docker run --env CYPRESS_MAIN_SERVICE=$MAIN_SERVICE --network=host --name e2e-tests-${CI_COMMIT_REF_SLUG} e2e-tests:${CI_COMMIT_REF_SLUG}
  after_script:
    - docker-compose -f compose.e2e.yml down --rmi all || true
    - docker cp e2e-tests-${CI_COMMIT_REF_SLUG}:/workdir/test-results.xml e2e-test-results.xml || true
    - docker cp e2e-tests-${CI_COMMIT_REF_SLUG}:/workdir/cypress/videos . || true
    - docker cp e2e-tests-${CI_COMMIT_REF_SLUG}:/workdir/cypress/screenshots . || true
    - docker rm e2e-tests-${CI_COMMIT_REF_SLUG} || true
    - docker rmi e2e-tests:${CI_COMMIT_REF_SLUG} || true
  artifacts:
    when: always
    paths:
      - e2e-test-results.xml
      - videos/**/*.mp4
      - screenshots/**/*.png
    reports:
      junit: e2e-test-results.xml
    expire_in: 1 day

container_scanning:
  stage: e2e
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}

remove-container:
  stage: cleanup
  dependencies: []
  image: 
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  before_script:
    - /bin/skopeo login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
    - /bin/skopeo delete docker://${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG}
  except:
    variables:
      - $CI_COMMIT_TAG

release:
  stage: release
  dependencies: []
  rules:
    - if: $CI_COMMIT_TAG != null
      when: manual
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - release-cli create
        --name "Turing-${CI_COMMIT_TAG}"
        --description "A docker image is available at ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG} & ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} or with the latest tag"
        --tag-name "${CI_COMMIT_TAG}"

add-latest-tag:
  stage: release
  dependencies: []
  rules:
    - if: $CI_COMMIT_TAG != null
  needs:
    - 'release'
  image: 
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  before_script:
    - /bin/skopeo login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/frontend:latest
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/backend:latest
    - /bin/skopeo copy docker://${CI_REGISTRY_IMAGE}/reverse-proxy:${CI_COMMIT_REF_SLUG} docker://${CI_REGISTRY_IMAGE}/reverse-proxy:latest
