services:
  backend:
    image: registry.mygit.th-deg.de/jd17123/enigma/backend:latest
    volumes:
      - type: bind
        source: ./enigma.yaml
        target: /etc/enigma.yaml
        read_only: true
    ports:
      - 5000:5000
  frontend:
    image: registry.mygit.th-deg.de/jd17123/enigma/frontend:latest
    ports:
      - 8080:80
