services:
  backend:
    build:
      context: backend
      args:
        context: local
    image: localhost/backend:latest
    environment:
      - FLASK_DEBUG=1
  frontend:
    build: frontend
    image: localhost/frontend:latest
