version: "2"
services:
  backend:
    image: registry.mygit.th-deg.de/jd17123/enigma/backend:latest
    volumes:
      - type: bind
        source: ./enigma.yaml
        target: /etc/enigma.yaml
        read_only: true
  frontend:
    image: registry.mygit.th-deg.de/jd17123/enigma/frontend:latest
  reverse-proxy:
    image: registry.mygit.th-deg.de/jd17123/enigma/reverse-proxy:latest
    ports:
      - 8000:80
