[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "backend"
version = "1.0.0"
dependencies = [
  "Flask == 2.2",
  "PyYaml == 6.0",
]

[tool.bandit]
exclude_dirs = ["tests"]
