ARG registry=docker.io
FROM ${registry}/cypress/browsers:node16.16.0-chrome107-ff107-edge
ENV browser=electron

COPY E2E_Enigma /workdir
WORKDIR /workdir
RUN mkdir /workdir/reports

RUN npm ci

CMD ["npx", "cypress", "run", "--headless", "--reporter", "junit", "--reporter-options", "mochaFile=/workdir/reports/e2e-test-[hash].xml,toConsole=true", "--browser", "${browser}"]
